# Actividad 1 - Numpy vs Tensorflow

**Objetivo:** El mayor problema al empezar con Keras y Deep Learning no es la matemática de la red neuronal, sino asegurarse de que los datos tienen las dimensiones (*shapes*) y los tipos correctos. En esta práctica vamos a perderle el miedo a manipular tensores, realizar operaciones matemáticas ágiles y aprender a convivir entre Numpy y TensorFlow.

[API de Tensorflow](https://tensorflow.org/api_docs)

### Parte 1: El Puente entre Numpy y TensorFlow
Las redes neuronales de Keras se alimentan de Tensores, pero en el mundo del Big Data, la limpieza inicial suele hacerse con Pandas y Numpy. Vamos a comprobar lo fácil que es pasar de un mundo a otro.

**El Reto:**
1. Importa las librerías necesarias.
2. Crea un array de Numpy de 1 dimensión con los números del 1 al 9.
3. Conviértelo en un Tensor de TensorFlow.
4. Vuelve a convertir ese Tensor a un array de Numpy.

In [3]:
import numpy as np
import tensorflow as tf

print(f"Versión de TF: {tf.__version__}")

# 1. Array en Numpy (Crea un array con los números del 1 al 9)
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Tipo en Numpy:", type(np_array))

# 2. Convertir a Tensor
tensor_1d = tf.convert_to_tensor(np_array)
print("Tipo en TF:", type(tensor_1d))
print("Tensor:", tensor_1d)

# 3. Vuelta a Numpy
back_to_numpy = np.array(tensor_1d)
print("De vuelta a Numpy:", type(back_to_numpy))

Versión de TF: 2.21.0
Tipo en Numpy: <class 'numpy.ndarray'>
Tipo en TF: <class 'tensorflow.python.framework.ops.EagerTensor'>
Tensor: tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int64)
De vuelta a Numpy: <class 'numpy.ndarray'>


### Parte 2: Jugando con el "Shape" (Dimensiones)
Una imagen en escala de grises de 28x28 píxeles tiene un *shape* de `(28, 28)`. Si le añadimos el canal de color (RGB), será `(28, 28, 3)`. Y si pasamos un lote (*batch*) de 32 imágenes a la red, será `(32, 28, 28, 3)`. Hay que dominar la función `tf.reshape`.

**El Reto:**
1. Crea un tensor constante con los números del 1 al 24.
2. Comprueba su `.shape` (verás que es un vector plano).
3. Redimensiónalo a una matriz de 4 filas y 6 columnas (2D).
4. Redimensiónalo a un tensor 3D de dimensiones `(2, 3, 4)`.

In [10]:
# 1. Tensor inicial (1D) con los números del 1 al 24
lista = []
for num in range(1, 25):
    lista.append(num)
tensor_base = tf.constant(lista)
print("Shape original:", tensor_base.shape)

# 2. Redimensionar a Matriz 2D (4x6)
tensor_2d = tf.reshape(tensor_base, (4, 6))
print("\nTensor 2D (4x6):\n", tensor_2d)
print("Nuevo shape:", tensor_2d.shape)

# 3. Redimensionar a Tensor 3D (2 bloques de 3x4)
tensor_3d = tf.reshape(tensor_2d, (2, 3, 4))
print("\nTensor 3D (2x3x4):\n", tensor_3d)
print("Shape 3D:", tensor_3d.shape)

Shape original: (24,)

Tensor 2D (4x6):
 tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]], shape=(4, 6), dtype=int32)
Nuevo shape: (4, 6)

Tensor 3D (2x3x4):
 tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
Shape 3D: (2, 3, 4)


### Parte 3: Casting de Tipos de Datos (El error silencioso)
En Deep Learning, la precisión decimal es clave para que los gradientes se actualicen correctamente. Por defecto, un tensor creado con enteros es de tipo `int32`, pero las redes neuronales en Keras esperan casi siempre `float32`.

**El Reto:**
1. Crea un tensor con los valores `[10, 20, 30]`.
2. Imprime su tipo de dato (`.dtype`).
3. Fuerza la conversión (*casting*) de ese tensor a `float32`.

In [11]:
# 1. Tensor de enteros
tensor_enteros = tf.constant([10, 20, 30])
print("Dtype original:", tensor_enteros.dtype)

# 2. Conversión a coma flotante (float32)
tensor_floats = tf.cast(tensor_enteros, tf.float32)
print("Dtype tras casting:", tensor_floats.dtype)
print("Tensor final:", tensor_floats)

Dtype original: <dtype: 'int32'>
Dtype tras casting: <dtype: 'float32'>
Tensor final: tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)


### Parte 4: Matemáticas y Ejecución Eager
Gracias a la ejecución *Eager* de TensorFlow 2.x, podemos operar con tensores de forma tan natural como si fueran variables básicas de Python. Además, TensorFlow soporta el *broadcasting* (expandir dimensiones automáticamente si sumas un escalar a una matriz).

**El Reto:**
1. Crea un tensor constante con los valores `[2, 4, 6]`.
2. Súmale un escalar (el número 10) a todo el tensor de golpe.
3. Multiplica el tensor original por sí mismo (multiplicación elemento a elemento, no matricial).

In [13]:
# 1. Tensor base
tensor_a = tf.constant([2, 4, 6])
print("Tensor A:", tensor_a)

# 2. Sumar un escalar (Broadcasting)
tensor_suma = tensor_a + 10
print("Suma con escalar:", tensor_suma)

# 3. Multiplicación elemento a elemento
tensor_mult = tensor_suma * tensor_suma
print("Multiplicación:", tensor_mult)

Tensor A: tf.Tensor([2 4 6], shape=(3,), dtype=int32)
Suma con escalar: tf.Tensor([12 14 16], shape=(3,), dtype=int32)
Multiplicación: tf.Tensor([144 196 256], shape=(3,), dtype=int32)


### Parte 5: Creación de Tensores Especiales (Simulando Pesos)
Cuando construyamos redes neuronales en Keras en las próximas sesiones, la librería inicializará automáticamente los pesos y los *bias*. Lo que hace bajo el capó es generar tensores de ceros, unos o valores aleatorios. Vamos a hacerlo a mano.

**El Reto:**
1. Crea un tensor de ceros de dimensiones `(3, 3)`.
2. Crea un tensor de unos de dimensiones `(2, 4)`.
3. Crea un tensor de dimensiones `(3, 3)` lleno de valores aleatorios extraídos de una distribución normal.

In [15]:
# 1. Tensor de ceros (3x3)
tensor_ceros = tf.zeros((3, 3))
print("Ceros:\n", tensor_ceros)

# 2. Tensor de unos (2x4)
tensor_unos = tf.ones((2, 4))
print("\nUnos:\n", tensor_unos)

# 3. Tensor aleatorio (Distribución Normal)
tensor_aleatorio = tf.random.normal((3, 3))
print("\nAleatorio (Normal):\n", tensor_aleatorio)

Ceros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)

Unos:
 tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)

Aleatorio (Normal):
 tf.Tensor(
[[ 0.60166466  0.1640807  -0.982489  ]
 [ 0.07420519 -0.6092806   0.26734072]
 [-0.19877684  2.2052853  -0.11102219]], shape=(3, 3), dtype=float32)


### Parte 6: Indexación y Slicing
El *Slicing* (cortar partes de un tensor) funciona exactamente igual que en Numpy y en las listas de Python, pero es vital dominarlo para cuando queramos extraer imágenes específicas de un lote (*batch*).

**El Reto:**
1. A partir de la matriz que te proporcionamos, extrae **solo la primera fila**.
2. Extrae **solo la última columna**.
3. Extrae la **submatriz central** (los números 4, 5, 7 y 8).

In [24]:
# Te damos este tensor de partida (Matriz 3x3)
matriz = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Matriz original:\n", matriz)

# 1. Extraer la primera fila
primera_fila = matriz[0:1]
print("\nPrimera fila:", primera_fila)

# 2. Extraer la última columna
ultima_columna = matriz[:, -1]
print("Última columna:", ultima_columna)

# 3. Extraer la submatriz central (valores 4,5 y 7,8)
submatriz = matriz[1:3, 0:2]
print("\nSubmatriz central:\n", submatriz)

Matriz original:
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

Primera fila: tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
Última columna: tf.Tensor([3 6 9], shape=(3,), dtype=int32)

Submatriz central:
 tf.Tensor(
[[4 5]
 [7 8]], shape=(2, 2), dtype=int32)


### Parte 7: Construyendo un Perceptrón a mano
En la UT3 visteis que una neurona artificial (Perceptrón) recibe unos datos de entrada ($X$), los multiplica por unos pesos ($W$) y les suma un sesgo o bias ($b$). La fórmula matemática es: $Y = X \cdot W + b$.

Keras hace esto por nosotros automáticamente, pero hoy vamos a demostrar que sois capaces de hacerlo con TensorFlow puro utilizando la multiplicación de matrices (`tf.matmul`).

**El Reto:**
1. Crea un tensor `X` (tus datos de entrada) de dimensiones `(3, 2)` con valores aleatorios normales. Imagina que son 3 casas, y de cada casa tenemos 2 datos (metros cuadrados y habitaciones).
2. Crea un tensor `W` (los pesos de la red) de dimensiones `(2, 1)` relleno de unos (`tf.ones`).
3. Crea un tensor `b` (el bias) que sea un tensor constante con el valor `[5.0]`.
4. Calcula la salida de la neurona haciendo la multiplicación matricial de `X` por `W` y sumándole `b`.

In [28]:
# 1. Datos de entrada: 3 ejemplos, 2 características
X =  tf.random.normal((3, 2))
print("Datos X:\n", X)

# 2. Pesos de la conexión
W =  tf.ones((2, 1))
print("\nPesos W:\n", W)

# 3. Bias (Sesgo)
b =  tf.constant(5.0)

# 4. Propagación hacia adelante (Forward pass): Y = X*W + b
# OJO: Se usa tf.matmul() para la multiplicación de matrices, el operador '*' normal daría error de dimensiones.
Y =  tf.matmul(X, W) + b
print("\nSalida final de la neurona (Y):\n", Y)

Datos X:
 tf.Tensor(
[[-0.25271013  0.6090807 ]
 [ 1.2400138   1.7983134 ]
 [-0.8818754  -0.25272292]], shape=(3, 2), dtype=float32)

Pesos W:
 tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)

Salida final de la neurona (Y):
 tf.Tensor(
[[5.3563704]
 [8.038327 ]
 [3.8654017]], shape=(3, 1), dtype=float32)
