# Práctica 2 de NumPy - Manipulación de Matrices

Practica para seguir trabajando con la librería Numpy.

Vas a tener que investigar funciones nuevas por lo que es altamente recomendado que te sumerjas en la documentación oficial de la librería y te vayas familiarizando con todo.

Enlace oficial: https://numpy.org/doc/stable/reference/index.html

### Ejercicio 1
Crea un array 2D de tamaño 5x5 con valores enteros aleatorios entre 0 y 50 y muestra la matriz junto con su forma y tamaño.

In [3]:
import numpy as np

array5x5 = np.random.randint(0, 50, (5, 5))
print(array5x5, "\n")
print(f"Forma: {array5x5.shape} \n")
print(f"Tamaño: {array5x5.size}")

[[29  6 44 12 20]
 [ 5  1 24 14 32]
 [ 8  9 40 32  2]
 [41 13  2 42 19]
 [42 34 21 30 43]] 

Forma: (5, 5) 

Tamaño: 25


### Ejercicio 2
Crea un array 1D de 20 elementos con valores consecutivos de 10 a 29 y luego reorganízalo en una matriz 4x5.

In [4]:
array1d = np.arange(10, 30)
print(array1d, "\n")
array4x5 = array1d.reshape(4,5)
print(array4x5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29] 

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### Ejercicio 3
Dada una matriz 6x6 de valores aleatorios entre 0 y 100, extrae todas las filas pares y columnas impares.

In [5]:
matriz6x6 = np.random.randint(0,100,(6,6))
print(matriz6x6, "\n")
print(matriz6x6[::2,1::2])

[[21 68 37  8 14 54]
 [15 51 64 20 89  3]
 [53 23 51 87 22 39]
 [23 64 49 48  5 49]
 [10 98 55 92 89 49]
 [67 53 32 98 12 97]] 

[[68  8 54]
 [23 87 39]
 [98 92 49]]


### Ejercicio 4
Crea una matriz de identidad de tamaño 7x7 y reemplaza la diagonal principal por números aleatorios enteros entre 1 y 10.

In [6]:
matriz7x7 = np.identity(7, dtype=int)
np.fill_diagonal(matriz7x7, np.random.randint(1,10))
print(matriz7x7)

[[2 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 2 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 0 2]]


### Ejercicio 5
Genera dos matrices 3x3 de valores aleatorios enteros entre 0 y 10 y calcula su suma, resta, multiplicación elemento a elemento y producto matricial.

In [7]:
matriz3x3_1 = np.random.randint(0,10,(3,3))
matriz3x3_2 = np.random.randint(0,10,(3,3))
print("Matriz 1:")
print(matriz3x3_1, "\n")
print("Matriz 2:")
print(matriz3x3_2, "\n")
print("Suma:")
print(matriz3x3_1 + matriz3x3_2, "\n")
print("Resta:")
print(matriz3x3_1 - matriz3x3_2, "\n")
print("Multiplicación elemento a elemento:")
print(matriz3x3_1 * matriz3x3_2, "\n")
print("Producto matricial:")
print(matriz3x3_1 @ matriz3x3_2)

Matriz 1:
[[3 0 8]
 [0 6 6]
 [6 5 4]] 

Matriz 2:
[[5 2 4]
 [3 7 6]
 [9 2 7]] 

Suma:
[[ 8  2 12]
 [ 3 13 12]
 [15  7 11]] 

Resta:
[[-2 -2  4]
 [-3 -1  0]
 [-3  3 -3]] 

Multiplicación elemento a elemento:
[[15  0 32]
 [ 0 42 36]
 [54 10 28]] 

Producto matricial:
[[87 22 68]
 [72 54 78]
 [81 55 82]]


### Ejercicio 6
Crea un array de 10 elementos aleatorios entre 0 y 1, calcula su media, desviación estándar y normalízalo.

In [8]:
array1d = np.random.random(10)
print("Array 1D:")
print(array1d, "\n")
print(f"Media: {array1d.mean()}")
print(f"Desviación estándar: {array1d.std()}")
array_normalizado = (array1d - array1d.min()) / (array1d.max() - array1d.min())
print("Array normalizado:")
print(array_normalizado)

Array 1D:
[0.84575314 0.28534238 0.16503269 0.35282086 0.48863956 0.40038493
 0.52614114 0.59763225 0.22905702 0.00932437] 

Media: 0.39001283472614146
Desviación estándar: 0.22648542373878275
Array normalizado:
[1.         0.32999584 0.1861585  0.41067035 0.57304962 0.467536
 0.61788497 0.70335682 0.26270337 0.        ]


### Ejercicio 7
Crea una matriz 5x5 con valores enteros aleatorios entre 1 y 100 y encuentra el índice de los elementos mínimo y máximo.

In [9]:
matriz5x5 = np.random.randint(1, 100, (5, 5))
print("Matriz original:")
print(matriz5x5, "\n")
indice_min = matriz5x5.argmin()
indice_max = matriz5x5.argmax()
print(f"Índice del valor mínimo: {indice_min}")
print(f"Índice del valor máximo: {indice_max}")

Matriz original:
[[10 68 72 18 15]
 [51 99 74 58 79]
 [35 76 61 53 58]
 [31 10 83 96 53]
 [73 69 24 43 63]] 

Índice del valor mínimo: 0
Índice del valor máximo: 6


### Ejercicio 8
Crea una matriz 4x4 con valores aleatorios enteros entre 0 y 20, inserta una fila [100,100,100,100] en la segunda posición y luego elimina la última columna.

In [ ]:
matriz4x4 = np.random.randint(0, 20, (4, 4))
print("Matriz 4x4:")
print(matriz4x4, "\n")
matriz4x4 = np.insert(matriz4x4, 2, [100,100,100,100], axis=0)
print(matriz4x4, "\n")
# axis se refiere a la dimensión: 0 para filas, 1 para columnas, al decirle -1 se refiere a que elimine
# el último elemento de esa dimensión
matriz4x4 = np.delete(matriz4x4, -1, axis=1)
print(matriz4x4)

Matriz 4x4:
[[ 4  9  1  6]
 [ 5  7  9  1]
 [ 0  2  2  0]
 [ 0 13 16 10]] 

[[  4   9   1   6]
 [  5   7   9   1]
 [100 100 100 100]
 [  0   2   2   0]
 [  0  13  16  10]] 

[[  4   9   1]
 [  5   7   9]
 [100 100 100]
 [  0   2   2]
 [  0  13  16]]


### Ejercicio 9
Genera una matriz 5x5 de valores aleatorios enteros entre 0 y 50 y reemplaza todos los valores mayores que 25 por 25.

In [32]:
matriz5x5 = np.random.randint(0, 50, (5, 5))
print("Matriz original:")
print(matriz5x5, "\n")
matriz5x5[matriz5x5 > 25] = 25
print("Matriz reemplazada:")
print(matriz5x5)

Matriz original:
[[ 0 17 27 25 23]
 [ 3 14 14 42 48]
 [14 22 14 15  4]
 [14 47 31 10 36]
 [34 24 19 12 19]] 

Matriz reemplazada:
[[ 0 17 25 25 23]
 [ 3 14 14 25 25]
 [14 22 14 15  4]
 [14 25 25 10 25]
 [25 24 19 12 19]]


### Ejercicio 10
Crea una matriz 3x4 de números aleatorios y ordénala por filas de menor a mayor.

In [36]:
matriz3x4 = np.random.randint(0, 50, (3, 4))
print("Matriz original:")
print(matriz3x4, "\n")
matriz3x4.sort(axis=1)
print("Matriz ordenada por filas:")
print(matriz3x4)

Matriz original:
[[ 3 33 46  5]
 [23 34 33 25]
 [17  7  5 24]] 

Matriz ordenada por filas:
[[ 3  5 33 46]
 [23 25 33 34]
 [ 5  7 17 24]]
