# Práctica 2 de NumPy - Manipulación de Matrices

Practica para seguir trabajando con la librería Numpy.

Vas a tener que investigar funciones nuevas por lo que es altamente recomendado que te sumerjas en la documentación oficial de la librería y te vayas familiarizando con todo.

Enlace oficial: https://numpy.org/doc/stable/reference/index.html

### Ejercicio 1
Crea un array 2D de tamaño 5x5 con valores enteros aleatorios entre 0 y 50 y muestra la matriz junto con su forma y tamaño.

In [3]:
import numpy as np

array5x5 = np.random.randint(0, 50, (5, 5))
print(array5x5, "\n")
print(f"Forma: {array5x5.shape} \n")
print(f"Tamaño: {array5x5.size}")

[[49 15 31 11 44]
 [31 40 17 18 30]
 [ 6 22 39 35  1]
 [45  1 25 36 29]
 [ 3 44 26 32  0]] 

Forma: (5, 5) 

Tamaño: 25


### Ejercicio 2
Crea un array 1D de 20 elementos con valores consecutivos de 10 a 29 y luego reorganízalo en una matriz 4x5.

In [5]:
array1d = np.arange(10, 30)
print(array1d, "\n")
array4x5 = array1d.reshape(4,5)
print(array4x5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29] 

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### Ejercicio 3
Dada una matriz 6x6 de valores aleatorios entre 0 y 100, extrae todas las filas pares y columnas impares.

In [8]:
matriz6x6 = np.random.randint(0,100,(6,6))
print(matriz6x6, "\n")
print(matriz6x6[::2,1::2])

[[36  0 14 78 69 91]
 [88 10 24 39 44 68]
 [ 8 66 95 99 17  7]
 [96 14 92 12 31 57]
 [ 4 70 91 61 38 47]
 [ 9 28 75  2 77 67]] 

[[ 0 78 91]
 [66 99  7]
 [70 61 47]]


### Ejercicio 4
Crea una matriz de identidad de tamaño 7x7 y reemplaza la diagonal principal por números aleatorios enteros entre 1 y 10.

In [26]:
matriz7x7 = np.identity(7, dtype=int)
np.fill_diagonal(matriz7x7, np.random.randint(1,10))
print(matriz7x7)

[[7 0 0 0 0 0 0]
 [0 7 0 0 0 0 0]
 [0 0 7 0 0 0 0]
 [0 0 0 7 0 0 0]
 [0 0 0 0 7 0 0]
 [0 0 0 0 0 7 0]
 [0 0 0 0 0 0 7]]


### Ejercicio 5
Genera dos matrices 3x3 de valores aleatorios enteros entre 0 y 10 y calcula su suma, resta, multiplicación elemento a elemento y producto matricial.

In [35]:
matriz3x3_1 = np.random.randint(0,10,(3,3))
matriz3x3_2 = np.random.randint(0,10,(3,3))
print("Matriz 1:")
print(matriz3x3_1, "\n")
print("Matriz 2:")
print(matriz3x3_2, "\n")
print("Suma:")
print(matriz3x3_1 + matriz3x3_2, "\n")
print("Resta:")
print(matriz3x3_1 - matriz3x3_2, "\n")
print("Multiplicación elemento a elemento:")
print(matriz3x3_1 * matriz3x3_2, "\n")
print("Producto matricial:")
print(matriz3x3_1 @ matriz3x3_2)

Matriz 1:
[[8 5 2]
 [7 2 9]
 [4 3 3]] 

Matriz 2:
[[7 7 7]
 [2 4 2]
 [9 1 0]] 

Suma:
[[15 12  9]
 [ 9  6 11]
 [13  4  3]] 

Resta:
[[ 1 -2 -5]
 [ 5 -2  7]
 [-5  2  3]] 

Multiplicación elemento a elemento:
[[56 35 14]
 [14  8 18]
 [36  3  0]] 

Producto matricial:
[[ 84  78  66]
 [134  66  53]
 [ 61  43  34]]


### Ejercicio 6
Crea un array de 10 elementos aleatorios entre 0 y 1, calcula su media, desviación estándar y normalízalo.

### Ejercicio 7
Crea una matriz 5x5 con valores enteros aleatorios entre 1 y 100 y encuentra el índice de los elementos mínimo y máximo.

### Ejercicio 8
Crea una matriz 4x4 con valores aleatorios enteros entre 0 y 20, inserta una fila [100,100,100,100] en la segunda posición y luego elimina la última columna.

### Ejercicio 9
Genera una matriz 5x5 de valores aleatorios enteros entre 0 y 50 y reemplaza todos los valores mayores que 25 por 25.

### Ejercicio 10
Crea una matriz 3x4 de números aleatorios y ordénala por filas de menor a mayor.