# Ejercicios NumPy

Tras hacer tus propias pruebas con la teoría de NumPy, completa los siguientes ejercicios en orden

---
## Ejercicio 1

Antes de empezar a trabajar de verdad, tendrás que importar la librería de NumPy para poder trabajar con ella:

In [2]:
import numpy as np

---
## Ejercicio 2

Crea un array de **una dimensión** con los 10 valores que tu quieras y muéstralo por pantalla:

In [3]:
array1d = np.array([1,2,3,4,5,6,7,8,9,10])
print(array1d)

[ 1  2  3  4  5  6  7  8  9 10]


---
## Ejercicio 3

Crea un array de distinto nombre al anterior de **dos dimensiones** con los 3x3 valores que tu quieras y muéstrala por pantalla:

In [4]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


---
## Ejercicio 4

Crea un array de distinto nombre a los anteriores de **tres dimensiones** con los 2x2x2 valores que tu quieras y muéstrala por pantalla:

In [5]:
array3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


---
## Ejercicio 5

Muestra las dimensiones, el tamaño y la forma que tienen las tres matrices creadas anteriormente:

In [6]:
print("Dimensiones")
print("Array 1D:", array1d.ndim)
print("Array 2D:", array2d.ndim)
print("Array 3D:", array3d.ndim)
print("Tamaños")
print("Array 1D:", array1d.size)
print("Array 2D:", array2d.size)
print("Array 3D:", array3d.size)
print("Formas")
print("Array 1D:", array1d.shape)
print("Array 2D:", array2d.shape)
print("Array 3D:", array3d.shape)

Dimensiones
Array 1D: 1
Array 2D: 2
Array 3D: 3
Tamaños
Array 1D: 10
Array 2D: 9
Array 3D: 8
Formas
Array 1D: (10,)
Array 2D: (3, 3)
Array 3D: (2, 2, 2)


---
## Ejercicio 6

Crea un array de una dimensión de tipo int8. En una de las posiciones pon el valor 1000. ¿Qué ocurre y porqué?

In [21]:
arrayInt8 = np.array([1,2,3,4,1000], dtype=np.int8)
print(arrayInt8)
# Da error al crear el array porque 1000 excede el rango de int8 (-128 a 127)
# int8 son 8 bits, 2^8 = 256 valores posibles, desde -128 hasta 127

OverflowError: Python integer 1000 out of bounds for int8

---
## Ejercicio 7

Crea un array de dos dimensiones de tipo float128 y luego muestra su tipo por pantalla:

In [ ]:
# Lo pongo en float64 porque float128 no existe en numpy
array2dFloat = np.array([[1.5,2.3,3.1],[4.7,5.6,6.4],[7.8,8.9,9.0]], dtype=np.float64)
print(array2dFloat.dtype)

float64


---
## Ejercicio 8

Crea un array con todos los múltiplos de 5 en una sola instrucción y muéstralo por pantalla:

In [ ]:
# Pongo hasta el 100 porque hay infinitos múltiplos de 5
multiplos5 = np.arange(5, 101, 5)
print(multiplos5)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


---
## Ejercicio 9

Crea un array con 20 valores entre los números 1 y 2. Estos valores deben estar distribuídos de manera equitativa:

In [25]:
arrayEntre1y2 = np.linspace(1, 2, 20)
print(arrayEntre1y2)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


---
## Ejercicio 10

Crea una matriz de forma 2x3 y muéstrala por pantalla. A continuación cambia su forma a una matriz 3x2

In [26]:
matrizReshape = np.array([[1,2,3],[4,5,6]])
print(matrizReshape, "\n")
matrizReshape = matrizReshape.reshape((3, 2))
print(matrizReshape)

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]]


---
## Ejercicio 11

Crea una matriz de 3x6 con valores aleatorios. Después muestra por pantalla las siguientes combinaciones:
*   La primera fila entera
*   La primera columna entera
*   Todos los valores entre las columnas 2 y 4
*   Todos los valores de las filas 1 y 2
*   Todos los valores entre las filas 2 y 3 y las columnas 5 y 6

In [52]:
matriz3x6 = np.random.randint(100, size=(3, 6))
print("Matriz entera")
print(matriz3x6, "\n")
print("Primera fila entera")
print(matriz3x6[0,:], "\n")
print("Primera columna entera")
print(matriz3x6[:,0], "\n")
print("Todos los valores entre las columnas 2 y 4")
print(matriz3x6[:,1:4], "\n")
print("Todos los valores de las filas 1 y 2")
print(matriz3x6[0:2,:], "\n")
print("Todos los valores entre las filas 2 y 3 y las columnas 5 y 6")
print(matriz3x6[1:3,4:6])

Matriz entera
[[75 82 53  8 80 34]
 [43 89 64 20 20 60]
 [85 25 50 18 26 48]] 

Primera fila entera
[75 82 53  8 80 34] 

Primera columna entera
[75 43 85] 

Todos los valores entre las columnas 2 y 4
[[82 53  8]
 [89 64 20]
 [25 50 18]] 

Todos los valores de las filas 1 y 2
[[75 82 53  8 80 34]
 [43 89 64 20 20 60]] 

Todos los valores entre las filas 2 y 3 y las columnas 5 y 6
[[20 60]
 [26 48]]


---
## Ejercicio 12

Crea un array de tamaño 1x5. Después añádele 5 elementos nuevos. Por último, elimina los dos primeros valores y muéstralo por pantalla:

In [54]:
array1x5 = np.array([1,2,3,4,5])
print("Array principal")
print(array1x5, "\n")
print("Array con 5 elementos más")
array1x5 = np.append(array1x5, [6,7,8,9,10])
print(array1x5, "\n")
print("Array con los 2 primeros valores eliminados")
array1x5 = np.delete(array1x5, [0,1])
print(array1x5)

Array principal
[1 2 3 4 5] 

Array con 5 elementos más
[ 1  2  3  4  5  6  7  8  9 10] 

Array con los 2 primeros valores eliminados
[ 3  4  5  6  7  8  9 10]


---
## Ejercicio 13

Crea dos matrices 3x3, una con valores aleatorios y otra de identidad. Realiza las cuatro operaciones básicas entre ellas (suma, resta, multiplicación y división). Por último, calcula la raíz cuadrada de matriz de identidad.

In [76]:
matriz3x3Random = np.random.randint(10, size=(3,3))
print("Matriz random")
print(matriz3x3Random, "\n")
matriz3x3Identidad = np.identity(3, dtype=int)
print("Matriz identidad")
print(matriz3x3Identidad, "\n")
print("Suma")
print(matriz3x3Random + matriz3x3Identidad, "\n")
print("Resta")
print(matriz3x3Random - matriz3x3Identidad, "\n")
print("Multiplicación")
print(matriz3x3Random * matriz3x3Identidad, "\n")
print("División")
# La división da algun warning porque no se puede dividir entre 0
print(matriz3x3Random / matriz3x3Identidad, "\n")
print("Raíz cuadrada de matriz de identidad")
print(np.sqrt(matriz3x3Identidad))

Matriz random
[[5 0 2]
 [0 2 2]
 [5 9 5]] 

Matriz identidad
[[1 0 0]
 [0 1 0]
 [0 0 1]] 

Suma
[[6 0 2]
 [0 3 2]
 [5 9 6]] 

Resta
[[4 0 2]
 [0 1 2]
 [5 9 4]] 

Multiplicación
[[5 0 0]
 [0 2 0]
 [0 0 5]] 

División
[[ 5. nan inf]
 [nan  2. inf]
 [inf inf  5.]] 

Raíz cuadrada de matriz de identidad
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


C:\Users\jperaltaza\AppData\Local\Temp\ipykernel_3012\1812462332.py:15: RuntimeWarning: divide by zero encountered in divide
  print(matriz3x3Random / matriz3x3Identidad, "\n")
C:\Users\jperaltaza\AppData\Local\Temp\ipykernel_3012\1812462332.py:15: RuntimeWarning: invalid value encountered in divide
  print(matriz3x3Random / matriz3x3Identidad, "\n")


---
## Ejercicio 14

Sin utilizar las funciones std, mean y median de NumPy, programa dichas funcionalidades:

In [ ]:
def media(matriz):
    suma = 0
    longitud = 0
    for array in matriz:
        for num in array:
            suma += num
            longitud += 1
    return suma / longitud

#TODO Adaptarlo a matriz, está hecho para un array
def mediana(matriz):
    longMatriz = len(matriz)
    if longMatriz % 2 != 0:
        # Divido la longitud / 2 para sacar la mitad de la matriz, como va a dar decimal porque es impar (*.5) le sumo 0,5 para
        # que no sea decimal y lo que salga sea la posición del número central (la misma cantidad de números por la izq y der).
        # Le resto 1 porque la posición en la matriz empieza desde 0
        # Lo convierto a int porque al hacer la división se convierte en float
        return matriz[int(longMatriz / 2 + 0.5 - 1)]
    else:
        # Resto 1 a pos1 porque las posiciones de las matrices empiezan en 0
        # A pos2 no le sumo 1 porque ya se resta 1 al empezar en 0
        pos1 = int(longMatriz / 2) - 1
        pos2 = int(longMatriz / 2)
        sumaNumCentrales = matriz[pos1] + matriz[pos2]
        return sumaNumCentrales
    
#def desviacion_estandar(matriz):
    #TODO


matrizPrueba = [[1,2],[3,4]]
print("Media: ", media(matrizPrueba))
print("Mediana: ", mediana(matrizPrueba))

Media:  2.5
Mediana:  [1, 2, 3, 4]


---
## Ejercicio 15

Compara los tiempos de ejecución entre las funciones que has creado anteriormente  y las de NumPy para matrices de tamaño 1.000.000 x 1.000.000 con valores aleatorios: